steps:
- name: 'asia.gcr.io/armbuilder/petalinux'
  args: ['bash', '-c', 'su peta_builder && petalinux-build']
  dir: './$REPO_NAME'
options:
  machineType: 'N1_HIGHCPU_8'
  logStreamingOption: STREAM_ON
artifacts:
  objects:
    location: 'gs://build_artifact_dudestin/'
    paths: ['./$REPO_NAME/images']
